Fix deployment

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -58,28 +58,39 @@ jobs:
     needs: setup
     if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
     steps:
-      -
-        name: Set up production Docker Buildx
-        id: production_builder
-        uses: docker/setup-buildx-action@v1
-      -
-        name: Login to DockerHub
-        uses: docker/login-action@v1
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
-        name: Determine Docker tag
-        id: docker_tag
-        run: |
-          # This run block will now only execute if the job's 'if' condition passed,
-          # meaning we are definitely on a push to 'main'.
+    -
+      name: Set up production Docker Buildx
+      id: production_builder
+      uses: docker/setup-buildx-action@v1
+    -
+      name: Login to DockerHub
+      uses: docker/login-action@v1
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+    -
+      name: Determine Docker tag
+      id: docker_tag
+      run: |
+        REF="${{ github.ref }}"
+        # Check if it's a push to the 'main' branch
+        if [[ "$REF" == "refs/heads/main" ]]; then
           echo "TAG=latest" >> $GITHUB_ENV
-      -
-        name: Build and push production container
-        uses: docker/build-push-action@v2
-        with:
-          push: true
-          builder: ${{ steps.production_builder.outputs.name }}
-          target: production
-          tags: namelivia/plants-client:${{ env.TAG }}
+        # Check if it's a push of a tag
+        elif [[ "$REF" =~ ^refs/tags/ ]]; then
+          TAG_NAME="${REF#refs/tags/}" # Removes 'refs/tags/' prefix
+          echo "TAG=$TAG_NAME" >> $GITHUB_ENV
+        else
+          echo "Error: Unhandled Git reference type: $REF"
+          exit 1
+        fi
+        echo "Determined Docker TAG: ${{ env.TAG }}"
+    -
+      name: Build and push production container
+      uses: docker/build-push-action@v2
+      with:
+        push: true
+        builder: ${{ steps.production_builder.outputs.name }}
+        target: production
+        tags: namelivia/plants-client:${{ env.TAG }}
+
